---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "hQnYu8wYwdkrDxq2WCHqnX2vb8lzhwAGMeUk4+YYQgdbJicE7kl0/Ca\
      ywoeJ3gvH2hkITu9wRgN2bwyWNI3KOzxHbYUkoQwH753AghZo4fxBrjEELG+zNgZ\
      IW2F3Bkwm+RjVTqEmzWsieniSETRS6gHMMCImiAsGtJbJsEqRO3HroXu/exPSD9F\
      eIKMNlduShe3gS1xcJttPz2vOy9EOZ7BS4qvM2lfE9CD4kq0OJOst4K1I0Or8QU0\
      mhbonn4uQAgyyffnafAKOfCEkjKDCfGjwAM9qvBIwF6Lxfp3O8GdSX2lDvqWQpSM\
      kBM0JkbbJMMfwe6z0gFDdwfAqq+i2g5XNJu//zsBmYumHv5wX/IUnYPCKpOBioKh\
      sFvlkDnfjN87QbtNrqi/tGPsF9KAhfA31ZORIrA3mvkSh0cIltU6SQOgWKAsQfWN\
      ant/7bezTURHFwbaARZqxTTGIUTM7Jr5Bg7P7WCRzyPK34WqnNpwR/zonREG4MHu\
      IYXjaohFUy1wJfpQ62m/GOcetU2UMoAiURbk3dQpvP4PrHWfCc18T2mxokGFxve/\
      VqvyTfeFKSGCK+2XLE2qaT13BZdF5YjdZNSyu+5xp5WiFD9pMOjQe1zdUSOLxYN0\
      FPkUaw5h6VN47fFsMmReNv7yv6br6uE/MSpKCK1wJUoxWO+u3PlI="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Ze/JC5lDRNJs2mVOHr5a1p9+8soJaylZNIMOjqktmQ71UytxyFz/Ii6\
      Q938pxMfa37coW7EBUX5WMCZGiGB95XQ1gippKNIWHko4UgfAcTPWY+exMBKEo8G\
      QE+w0ZdhtwvXeI4fXudO33C1fpUg+zCzi6uS6W4nFvkxRTE/69cBPL0SyrHvxLan\
      hODPAZL0t5BJKFGIOr0Qk2WryPtYMq0AuBnlXX8KqbCKzH+aAUM+KjDxMgvPiiw2\
      aq+/QRagumEzRteugh/Y+jisXmoZYC7tCmbHkHV+yX+v8/W4j7mZ1yw5OSLwqJi4\
      go1y/SE5NmCKVOf/gHu+ul+53XrQDuCtlN/ncBe0oOjGsHuhFPhKWHl4ZRsQOJkt\
      CgH+smRTZCwI8gON3Ai5vWS64THRacHTKaXo4lIuys9gLZxjXbSDKL+mM6jbFR2r\
      bl5eWh4HJyuTpHo7amiz0miRZOokm51uB/R+vhULkoJmwhCBpKOoHWyr62zou6Rw\
      +UozMOQI4yRxeUfiPbDVYkSBHvVg6d0F5u0ufyM/7dhkHHoI9+jJiBiXmQo3ik3b\
      1v51zdBvYQ5peT9xQqcDSL8RLfNROihHGbJWmuACNe5uHeBp0VmoA8s6HMll0Cuf\
      WCatpnhh3vv/amUvqAtqTlQlwt+m1t2lqjK0jwhaqCRfnd1whJxM="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
