---
# tasks file for cyhy_feeds

#
# Grab the cyhy-feeds code
#
- name: Create the /var/local/cyhy/feeds directory
  ansible.builtin.file:
    mode: 0755
    path: /var/local/cyhy/feeds
    state: directory

- name: Download and untar the cyhy-feeds tarball
  ansible.builtin.unarchive:
    src: "https://api.github.com/repos/cisagov/cyhy-feeds/tarball/develop"
    dest: /var/local/cyhy/feeds
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Create the /var/cyhy/scripts/cyhy-feeds/cyhy_extracts directory
  ansible.builtin.file:
    mode: 0755
    path: /var/cyhy/scripts/cyhy-feeds/cyhy_extracts
    state: directory

- name: Copy the extract scripts
  ansible.builtin.copy:
    src: "/var/local/cyhy/feeds/aws_jobs/{{ item }}"
    dest: "/var/cyhy/scripts/cyhy-feeds/{{ item }}"
    mode: 0755
    remote_src: yes
  loop:
    - cyhy-data-extract.py
    - dmarc.py

- name: Install dependencies required by the extract scripts
  ansible.builtin.package:
    name:
      - gnupg2
      - unzip

# This is necessary because the version of pip being used does not support
# PEP 508 style url version pinning which is what is being used in setup.py
# for the cyhy-feeds project.
- name: Install pip dependency mongo-db-from-config through url
  ansible.builtin.pip:
    name:
      - https://github.com/cisagov/mongo-db-from-config/tarball/develop

- name: Install other pip dependencies through requirements.txt
  ansible.builtin.pip:
    chdir: /var/local/cyhy/feeds
    requirements: requirements.txt
