---
#
# Grab the cyhy-feeds code
#
- name: Create the /var/local/cyhy/feeds directory
  ansible.builtin.file:
    group: "{{ cyhy_feeds_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_feeds_file_owner_username | default(omit) }}"
    path: /var/local/cyhy/feeds
    state: directory

- name: Download and untar the cyhy-feeds tarball
  ansible.builtin.unarchive:
    dest: /var/local/cyhy/feeds
    extra_opts:
      - --strip-components=1
    group: "{{ cyhy_feeds_file_owner_group | default(omit) }}"
    owner: "{{ cyhy_feeds_file_owner_username | default(omit) }}"
    remote_src: true
    src: https://api.github.com/repos/cisagov/cyhy-feeds/tarball/develop

- name: Create the /var/cyhy/scripts/cyhy-feeds/cyhy_extracts directory
  ansible.builtin.file:
    group: "{{ cyhy_feeds_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_feeds_file_owner_username | default(omit) }}"
    path: /var/cyhy/scripts/cyhy-feeds/cyhy_extracts
    state: directory

- name: Copy the extract scripts
  ansible.builtin.copy:
    dest: /var/cyhy/scripts/cyhy-feeds/{{ item }}
    group: "{{ cyhy_feeds_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_feeds_file_owner_username | default(omit) }}"
    remote_src: true
    src: /var/local/cyhy/feeds/aws_jobs/{{ item }}
  loop:
    - cyhy-data-extract.py
    - dmarc.py

- name: Install dependencies required by the extract scripts
  ansible.builtin.package:
    name:
      - gnupg2
      - unzip

# We only need this on Debian Buster, but we want this before the block
# that follows so we can use it in the `when`.
- name: Gather the package facts
  ansible.builtin.package_facts:
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'

- name: Remove python3-yaml system package (Debian Buster)
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
    - "'python3-yaml' in ansible_facts.packages"
  block:
    - name: Hold the python3-yaml system package to prevent reinstallation
      ansible.builtin.dpkg_selections:
        name: python3-yaml
        selection: hold

    - name: Remove python3-yaml system package
      ansible.builtin.command:
        # There are installed packages (aws-cli and cloud-init) that depend on
        # this system package. We ignore those dependencies since we'll be
        # installing the Python package in the following step.
        cmd: dpkg --force-depends --purge python3-yaml
      changed_when: "'purging' in dpkg_result.stdout or 'purging' in dpkg_result.stderr"
      failed_when:
        - dpkg_result.rc != 0
        - "'is not installed' not in dpkg_result.stderr"
      register: dpkg_result

- name: Install other pip dependencies through requirements.txt
  ansible.builtin.pip:
    chdir: /var/local/cyhy/feeds
    executable: pip3
    # The extra argument is necessary on modern platforms, which
    # correctly recognize that the local Python is externally managed
    # (i.e. managed via the system package manager and not by pip).
    extra_args: >-
      {{ (ansible_distribution in ['Kali']
      or (ansible_distribution in ['Debian', 'Ubuntu']
      and ansible_distribution_release not in ['buster', 'bullseye'])) |
      ternary('--break-system-packages', omit) }}
    requirements: requirements.txt
